language: node_js
node_js:
  - "6.0"
  - "6"
  - "7.0"
  - "7"
  - "8.0"
  - "8"
  - "9.0"
  - "9"
  - "10.0"
  - "10"
  - "11.0"
  - "11"
  - "12.0"
  - "12"
  - "13.0"
  - "13"
  - "node"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov

script:
  - npm run coverage

after_success:
  - codecov

jobs:
  include:
    - name: Lint
      node_js: "node"
      before_install: skip
      script:
        - npm run lint
      after_success: skip
    - stage: npm release
      if: tag IS present
      node_js: "node"
      cache: {}
      before_install: skip
      install: skip
      script: skip
      after_success: true  # Don't skip: To trigger the deploy
      deploy:
        provider: npm
        email: thinca+npm@gmail.com
        api_key:
          secure: gGKW8mkszAL6KlnYvhfE5wWZNA1USiPBTBCz2a+1zACCWS4H0m3Puw/kDISG6LfETOEfGfEUm33/SDnCBfFnBsFn/Ytyy8A9cyO5lPAqlfDCh8+BII6NqGxjhyJ+uBij5Se/ykcYqPaqmGomX11Z4gksOBYMSuzU5LMZm/SHVieKg+3oWmuSO43jF4pNeVi9L6xyKuKgtsuIcS71PikmQ2WrlmGc8ShRJ3IgKw6wDfqDVqMz7C1wO/Qa5dIENgz/r215drWP9Teh0dAsgihYrQpinI0DLw8Ir1dyQSe6Rt8D1TIjhJ1ztwrbVfFolQSwNeoYlGjneuBknCkFmudGF3Rgfy/OYQkXpZDE7gWtZqoo/GdYG8BPdGOR0gzSD6lqqrnGFnDn/61v/fCYhQ8pF16ShvDlW28IXtI0LjYhdhSd8f3iLgbm3AXDZpmD9hNe308s3eFmJDSJUkcEzcXuM23HzVQokyUGjMuHKt2pZY+ZyiihQCI9jmMPlnFvNhvV9MlhCO1joLRKvlwNTd1Z9xYvUpRVeX3iT50IjnFH77luYKZgOQoYHWYC2JdGSZfe14RgCiDyoVkoOF66Bx7FRpXpqF/ZvAuwE3IOJAqI+/7x2yGN6UTy4UJJquqShSZ55oARFCYzgzXuOqDhWIUpw/mIPi1xpfKuIDsyeCzXGCA=
        on:
          tags: true
