language: node_js
node_js:
  - "node"
  - "6.0"
  - "6"
  - "7.0"
  - "7"

sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run coverage

after_success:
  - npm run coveralls
