name: 'Lint'
on: ['push', 'pull_request']

jobs:
  lint:
    name: 'Run ESLint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v2-beta'
        with:
          node-version: '14'
      - uses: 'bahmutov/npm-install@v1'
      - name: 'Run ESLint'
        run: |
          npm run --silent lint
