name: 'Publish'
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: 'Publish'
    if: "github.event.workflow_run.conclusion == 'success'"
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - uses: 'bahmutov/npm-install@v1'
      - name: 'Prepare for publishing a new npm package'
        run: |
          npm run --silent build
      - name: 'Publish a new npm package'
        uses: 'JS-DevTools/npm-publish@v1'
        with:
          token: ${{ secrets.NPM_TOKEN }}
